name:                scripts-hs
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/pavelkogan/scripts-hs#readme
license:             BSD3
author:              Pavel Kogan
maintainer:          pkogan@gmail.com
copyright:           BSD3
category:            Web

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - TupleSections

ghc-options:
  - -Wall
  - -O2

executables:
  timelapse:
    source-dirs:      src
    main:             timelapse.hs
    dependencies:
      - friendly-time
      - time
  mvt:
    source-dirs:      src
    main:             mvt.hs
    dependencies:
      - extra
      - turtle
  tmsu-add-tags:
    source-dirs:      src
    main:             tmsu-add-tags.hs
    dependencies:
      - classy-prelude
      - exceptions
      - filepath
      - hzenity
      - optparse-applicative
      - path
      - path-io
      - text-conversions
      - typed-process
      - unliftio
